wiki/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *
from django.conf import settings

from wiki import views, models

try:
    WIKI_URL_RE = settings.WIKI_URL_RE
except AttributeError:
    WIKI_URL_RE = r'\w+'

urlpatterns = patterns('',
    url(r'^$', views.article_list, name='wiki_index'),

    url(r'^list/$', views.article_list, name='wiki_list'),

    url(r'^search/$', views.search_article, name="wiki_search"),

    url(r'^history/$', views.history, name='wiki_history'),

    url(r'^feeds/(?P<feedtype>\w+)/$', views.history_feed, name='wiki_history_feed'),

    url(r'^(?P<title>'+ WIKI_URL_RE +r')/feeds/(?P<feedtype>\w+)/$', views.article_history_feed,
        name='wiki_article_history_feed'),

    url(r'^(?P<title>'+ WIKI_URL_RE +r')/$', views.view_article,
        name='wiki_article'),

    url(r'^edit/(?P<title>'+ WIKI_URL_RE +r')/$', views.edit_article,
        name='wiki_edit'),

    url(r'^remove/(?P<title>'+ WIKI_URL_RE +r')/$', views.remove_article,
        name='wiki_remove_article'),

    url(r'observe/(?P<title>'+ WIKI_URL_RE +r')/$', views.observe_article,
        name='wiki_observe'),

    url(r'observe/(?P<title>'+ WIKI_URL_RE +r')/stop/$', views.stop_observing_article,
        name='wiki_stop_observing'),

    url(r'^history/(?P<title>'+ WIKI_URL_RE +r')/$', views.article_history,
        name='wiki_article_history'),

    url(r'^history/(?P<title>'+ WIKI_URL_RE +r')/changeset/(?P<revision>\d+)/$', views.view_changeset,
        name='wiki_changeset',),

    url(r'^history/(?P<title>'+ WIKI_URL_RE +r')/revert/$', views.revert_to_revision,
        name='wiki_revert_to_revision'),
)

wiki/models.py
from datetime import datetime
from django.core.urlresolvers import reverse

# Google Diff Match Patch library
# http://code.google.com/p/google-diff-match-patch
from diff_match_patch import diff_match_patch

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.db.models.query import QuerySet

from tagging.fields import TagField
from tagging.models import Tag

from wiki.utils import get_ct

try:
    from notification import models as notification
    from django.db.models import signals
except ImportError:
    notification = None

# We dont need to create a new one everytime
dmp = diff_match_patch()

def diff(txt1, txt2):
    """Create a 'diff' from txt1 to txt2."""
    patch = dmp.patch_make(txt1, txt2)
    return dmp.patch_toText(patch)

try:
    markup_choices = settings.WIKI_MARKUP_CHOICES
except AttributeError:
    markup_choices = (
        ('creole', _(u'Creole')),
        ('restructuredtext', _(u'reStructuredText')),
        ('textile', _(u'Textile')),
        ('markdown', _(u'Markdown')),
    )


# Avoid boilerplate defining our own querysets
class QuerySetManager(models.Manager):
    def get_query_set(self):
        return self.model.QuerySet(self.model)


class NonRemovedArticleManager(QuerySetManager):
    def get_query_set(self):
        q = super(NonRemovedArticleManager, self).get_query_set()
        return q.filter(removed=False)


class Article(models.Model):
    """ A wiki page.
    """
    title = models.CharField(_(u"Title"), max_length=50)
    content = models.TextField(_(u"Content"))
    summary = models.CharField(_(u"Summary"), max_length=150,
                               null=True, blank=True)
    markup = models.CharField(_(u"Content Markup"), max_length=3,
                              choices=markup_choices,
                              null=True, blank=True)
    creator = models.ForeignKey(User, verbose_name=_('Article Creator'),
                                null=True)
    creator_ip = models.IPAddressField(_("IP Address of the Article Creator"),
                                       blank=True, null=True)
    created_at = models.DateTimeField(default=datetime.now)
    last_update = models.DateTimeField(blank=True, null=True)
    removed = models.BooleanField(_("Is removed?"), default=False)

    content_type = models.ForeignKey(ContentType, null=True)
    object_id = models.PositiveIntegerField(null=True)
    group = generic.GenericForeignKey('content_type', 'object_id')

    tags = TagField()

    objects = QuerySetManager()

    non_removed_objects = NonRemovedArticleManager()

    class QuerySet(QuerySet):

        def get_by(self, title, group=None):
            if group is None:
                return self.get(title=title)
            return group.get_related_objects(self.filter(title=title)).get()
            
    class Meta:
        verbose_name = _(u'Article')
        verbose_name_plural = _(u'Articles')

    def get_absolute_url(self):
        if self.group is None:
            return reverse('wiki_article', args=(self.title,))
        return self.group.get_absolute_url() + 'wiki/' + self.title

    def save(self, force_insert=False, force_update=False):
        self.last_update = datetime.now()
        super(Article, self).save(force_insert, force_update)

    def remove(self):
        """ Mark the Article as 'removed'. If the article is
        already removed, delete it.
        Returns True if the article was deleted, False when just marked
        as removed.
        """
        if self.removed:
            self.delete()
            return True
        else:
            self.removed = True
            self.save()
            return False

    def latest_changeset(self):
        try:
            return self.changeset_set.filter(
                reverted=False).order_by('-revision')[0]
        except IndexError:
            return ChangeSet.objects.none()

    def new_revision(self, old_content, old_title, old_markup,
                     comment, editor_ip, editor):
        '''Create a new ChangeSet with the old content.'''

        content_diff = diff(self.content, old_content)

        cs = ChangeSet.objects.create(
            article=self,
            comment=comment,
            editor_ip=editor_ip,
            editor=editor,
            old_title=old_title,
            old_markup=old_markup,
            content_diff=content_diff)

        if None not in (notification, self.creator):
            if editor is None:
                editor = editor_ip
            notification.send([self.creator], "wiki_article_edited",
                              {'article': self, 'user': editor})

        return cs

    def revert_to(self, revision, editor_ip, editor=None):
        """ Revert the article to a previuos state, by revision number.
        """
        changeset = self.changeset_set.get(revision=revision)
        changeset.reapply(editor_ip, editor)


    def __unicode__(self):
        return self.title


class NonRevertedChangeSetManager(QuerySetManager):

    def get_default_queryset(self):
        super(NonRevertedChangeSetManager, self).get_query_set().filter(
              reverted=False)


class ChangeSet(models.Model):
    """A report of an older version of some Article."""

    article = models.ForeignKey(Article, verbose_name=_(u"Article"))

    # Editor identification -- logged or anonymous
    editor = models.ForeignKey(User, verbose_name=_(u'Editor'),
                               null=True)
    editor_ip = models.IPAddressField(_(u"IP Address of the Editor"))

    # Revision number, starting from 1
    revision = models.IntegerField(_(u"Revision Number"))

    # How to recreate this version
    old_title = models.CharField(_(u"Old Title"), max_length=50, blank=True)
    old_markup = models.CharField(_(u"Article Content Markup"), max_length=3,
                                  choices=markup_choices,
                                  null=True, blank=True)
    content_diff = models.TextField(_(u"Content Patch"), blank=True)

    comment = models.CharField(_(u"Editor comment"), max_length=50, blank=True)
    modified = models.DateTimeField(_(u"Modified at"), default=datetime.now)
    reverted = models.BooleanField(_(u"Reverted Revision"), default=False)

    objects = QuerySetManager()
    non_reverted_objects = NonRevertedChangeSetManager()

    class QuerySet(QuerySet):
        def all_later(self, revision):
            """ Return all changes later to the given revision.
            Util when we want to revert to the given revision.
            """
            return self.filter(revision__gt=int(revision))


    class Meta:
        verbose_name = _(u'Change set')
        verbose_name_plural = _(u'Change sets')
        get_latest_by  = 'modified'
        ordering = ('-revision',)

    def __unicode__(self):
        return u'#%s' % self.revision

    @models.permalink
    def get_absolute_url(self):
        if self.article.group is None:
            return ('wiki_changeset', (),
                    {'title': self.article.title,
                     'revision': self.revision})
        return ('wiki_changeset', (),
                {'group_slug': self.article.group.slug,
                 'title': self.article.title,
                 'revision': self.revision})


    def is_anonymous_change(self):
        return self.editor is None

    def reapply(self, editor_ip, editor):
        """ Return the Article to this revision.
        """

        # XXX Would be better to exclude reverted revisions
        #     and revisions previous/next to reverted ones
        next_changes = self.article.changeset_set.filter(
            revision__gt=self.revision).order_by('-revision')

        article = self.article

        content = None
        for changeset in next_changes:
            if content is None:
                content = article.content
            patch = dmp.patch_fromText(changeset.content_diff)
            content = dmp.patch_apply(patch, content)[0]

            changeset.reverted = True
            changeset.save()

        old_content = article.content
        old_title = article.title
        old_markup = article.markup

        article.content = content
        article.title = changeset.old_title
        article.markup = changeset.old_markup
        article.save()

        article.new_revision(
            old_content=old_content, old_title=old_title,
            old_markup=old_markup,
            comment="Reverted to revision #%s" % self.revision,
            editor_ip=editor_ip, editor=editor)

        self.save()

        if None not in (notification, self.editor):
            notification.send([self.editor], "wiki_revision_reverted",
                              {'revision': self, 'article': self.article})

    def save(self, force_insert=False, force_update=False):
        """ Saves the article with a new revision.
        """
        if self.id is None:
            try:
                self.revision = ChangeSet.objects.filter(
                    article=self.article).latest().revision + 1
            except self.DoesNotExist:
                self.revision = 1
        super(ChangeSet, self).save(force_insert, force_update)

    def display_diff(self):
        ''' Returns a HTML representation of the diff.
        '''

        # well, it *will* be the old content
        old_content = self.article.content

        # newer non-reverted revisions of this article, starting from this
        newer_changesets = ChangeSet.non_reverted_objects.filter(
            article=self.article,
            revision__gte=self.revision)

        # apply all patches to get the content of this revision
        for i, changeset in enumerate(newer_changesets):
            patches = dmp.patch_fromText(changeset.content_diff)

wiki/templates/wiki/article_content.html
{% load wiki_markup %}
{% load generic_markup %}


{{ content|apply_markup:markup }}

wiki/templates/wiki/article_teaser.html
{% load wiki_markup %}
{% load avatar_tags %}

<tr class="{% cycle odd,even %}">
    <td class="meta">
        <div class="avatar">{% avatar article.latest_changeset.editor 40 %}</div>
        <div class="details">
            <a href="{% url profiles.views.profile article.latest_changeset.editor.username %}">
                {{ article.latest_changeset.editor }}
            </a>
        </div>
        {{ article.last_update|date }}
    </td>
    <td>
        <h2><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h2>
        <div class="body">{% render_content article 'summary' %}</div>
    </td>
</tr>

wiki/templates/wiki/base.html
{% load i18n %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
            "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<title>{% block title %}{% endblock %} - WikiApp</title>
	<link rel="stylesheet" href="{% url wiki_static_media "wikiapp.css" %}">

</head>
<body>
    <div id="head">
      <h1>wikiapp</h1>
      {% include "wiki/searchbox.html" %}
    </div>

    <div id="actions">
      {% block footer %}{% endblock %}
      <a href="{% url wiki_list %}">{% trans "List all articles" %}</a> |
      <a href="{% url wiki_history %}">{% trans "Recent Changes" %}</a>
    </div>

    <div id="article">
      {% include "wiki/messages.html" %}
      {% block content %}{% endblock %}
    </div>

    <div id="footer">
      Powered by <a href="http://code.google.com/p/django-wikiapp">django-wikiapp</a>
    </div>
</body>
</html>

wiki/templates/wiki/changeset.html
{% extends 'wiki/base.html' %}
{% load i18n %}

{% block title %}
    Changes in {{ article_title }}
{% endblock %}

{% block content %}
	<h1> <a href="{% url wiki_article article_title %}"> {{ article_title }} </a> </h1>
    {% if changeset.old_title %}
        <h2> {{ changeset.old_title }} </h2>
    {% endif %}
    {{ changeset.display_diff|safe }}
    <br><b>{% trans "Markup:" %}</b>
    {% if changeset.old_markup %} {{ changeset.old_markup }}
    {% else %} {% trans "Plain Text." %}
    {% endif %}
{% endblock %}

wiki/templates/wiki/confirm_remove.html
{% extends 'wiki/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Remove article" %}
{% endblock %}

{% block content %}
	<h1>{% trans "Confirm deletion" %}</h1>

    You are about to remove the article "{{ article.title }}".

	<form action="" method="post">

		<div class="submit">
			<input type="submit" value="{% trans "Confirm" %}" />
		</div>

	</form>
{% endblock %}

wiki/templates/wiki/edit.html
{% extends 'wiki/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Editing article" %}
{% endblock %}

{% block content %}
	<h1>{% trans "Edit" %}</h1>

	<form action="" method="post">

        {{ form.as_p }}

		<div class="submit">
			<input type="submit" value="{% trans "Save" %}" />
		</div>

	</form>
{% endblock %}

wiki/templates/wiki/history.html
{% extends 'wiki/base.html' %}
{% load i18n %}


{% block title %}
    {% trans "History for" %} {{ article.title }}
{% endblock %}

{% block content %}
<h1>
  <a href="{{ article.get_absolute_url }}"> {{ article.title }} </a>
</h1>

<h2> {% trans "Article History" %} </h2>

<form action="{% url wiki_revert_to_revision article.title %}" method="post">
  <table>
    <tr class="tbheader">
	  <th>{% trans "At" %}</th>
	  <th>{% trans "User" %}</th>
	  <th>{% trans "Comment" %}</th>
	  <th>{% trans "Revert" %}</th>
    </tr>
    {% for change in changes %}
    <tr class="{% cycle 'tbodd' 'tbeven' %}">
    	<td><a href="{{ change.get_absolute_url }}">
    		{{ change.modified|date:"M d, Y" }}</a>
        </td>
    	<td>
        {% if change.is_anonymous_change %}
            {{ change.editor_ip }}
        {% else %}
            <a href="{% url wiki_article change.editor %}">{{ change.editor }}</a>
        {% endif %}
        </td>
        <td>
          {% if change.comment %}<i>'{{ change.comment}}'</i> {% endif %}
        </td>
        <td>
            {% if forloop.first %}
                {% trans "Current revision" %}
            {% else %}
                 <input id="id_revision" name="revision"
                        {% ifequal forloop.counter 2 %}checked{% endifequal %}
                        type="radio" value="{{ change.revision }}">
            {% endif %}
        </td>
    </tr>
    {% endfor %}
  </table>
  {% ifnotequal changes.count 1 %}
       <input type="submit" value="{% trans "Revert" %}">
  {% endifnotequal %}

</form>

<a href="{% url wiki_article_history_feed title=article.title,feedtype="atom" %}">Atom Feed</a>

{% endblock %}

wiki/templates/wiki/index.html
{% extends 'wiki/base.html' %}
{% load i18n %}


{% block title %}
    Index
{% endblock %}

{% block content %}
	<h1>Index</h1>

	{% if articles %}
		<ul>
			{% for article in articles %}
				<li><a href="{% url wiki_article article.title %}">{{ article.title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
        <p><a href="{% url wiki_edit "NewArticle" %}">{% trans "Create a new article" %}</a>.</p>
	{% endif %}
{% endblock %}

wiki/templates/wiki/messages.html
{% if messages %}
<ul id="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

wiki/templates/wiki/recentchanges.html
{% extends 'wiki/base.html' %}
{% load i18n %}

{% block content %}
<h2>{% trans "Recent Changes" %}</h2>
<table>
    <tr class="tbheader">
	  <th>{% trans "Action" %}</th>
	  <th>{% trans "Title" %}</th>
	  <th>{% trans "Date" %}</th>
	  <th>{% trans "Editor" %}</th>
	  <th>{% trans "Comment" %}</th>
    </tr>
    {% for change in changes %}
    <tr class="{% cycle 'tbodd' 'tbeven' %}">
        <td>
            {% if change.old_title %}
                <a href="{% url wiki_changeset change.article.title,change.revision %}"> Modified </a>
            {% else %}
                Added
            {% endif %}
        </td>
        <td><a href="{% url wiki_article change.article.title %}">
            {{ change.article.title }}</a>
        </td>
        <td>{{ change.modified|date:"H:i" }}</td>
        <td>
            {% if change.editor %}
                {{ change.editor }}
            {% else %}
                {{ change.editor_ip }}
            {% endif %}
        </td>
        <td>{{ change.comment }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

wiki/templates/wiki/searchbox.html
{% load i18n %}

{% if search_form %}
<div id="searchbox">
  <form method="post" action="{% url wiki_search %}">
    {{ search_form.as_p }}
    <input type="submit" name="search_button" value="{% trans "Article by title" %}" accesskey="t">
  </form>
</div>
{% endif %}

wiki/templates/wiki/view.html
{% extends 'wiki/base.html' %}
{% load i18n %}
{% load wiki_markup %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block content %}
	<h1><a href="{{ article.get_absolute_url }}" rel="bookmark">{{ article.title }}</a></h1>

	{% if not article.id %}
		<p>{% trans "This article does not exist." %}
          <a href="{% url wiki_edit article.title %}" {% trans ">Create it now</a>?" %}</p>
	{% endif %}

    {% render_content article %}

{% endblock %}

{% block footer %}
	{% if article.id %}
		<a href="{% url wiki_edit article.title %}">{% trans "Edit this article" %}</a>
        |
        <a href="{% url wiki_article_history article.title %}">{% trans "Editing history" %}</a>
        |
        <a href="{% url wiki_remove_article article.title %}">{% trans "Remove this article" %}</a>
	{% else %}
		<a href="{% url wiki_edit article.title %}">{% trans "Create this article" %}</a>
	{% endif %}
    |
{% endblock %}

wiki/templates/wiki/wiki_title.html
{% load i18n %}

{% blocktrans %}
    <h1> Wiki for {{ group_type }} <a href="{{ group_url }}">{{ group_name }}</a> </h1>
{% endblocktrans %}